name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Pagic
        run: deno install --unstable --allow-read --allow-write --allow-net --allow-env --allow-run --name=pagic https://deno.land/x/pagic/mod.ts

      - name: Build
        run: pagic build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: blog-deno
          entrypoint: app.ts
